### ISSUE TITLE
Prevent adding when multi-columns or flexbox

### ISSUE THREAD

**Issue by yepninja** [csstools/postcss-gap-properties#1]
Maybe it would be good to try to detect multi-column or flexbox layout and don't add a prefix in this case - less code and less wrong (unused) properties.

**Comment by chris-pearce** [comment]
Second this ⇧ as it's nice to use this `display` agnostic property across all `display` types. Currently, it's limited to `display: grid`.

**Comment by chris-pearce** [comment]
Sorry, I wasn't entirely clear. I guess I'm asking if this plugin can polyfill Flexbox and Multi-column displays, not just Grid? Thanks.

**Comment by lwyj123** [comment]
@yepninja according to https://drafts.csswg.org/css-align-3/#gaps, gap properties is not just for grid.

**Comment by yepninja** [comment]
@lwyj123 You are right! But this plugin adds `grid-` prefix not only for grid, but also for multi-columns and flexbox layout. For example:

It's okey:
```css
display: grid;
grid-gap: 1rem;
```

It's not okey:
```css
display: flex;
grid-gap: 1rem;
```
